name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.7', '3.0', '3.1']
        jekyll-version: ['~> 3.0', '~> 4.0']
        exclude:
          # Jekyll 3.x has compatibility issues with newer Ruby versions
          - ruby-version: '3.1'
            jekyll-version: '~> 3.0'
          - ruby-version: '3.0'
            jekyll-version: '~> 3.0'

    env:
      JEKYLL_VERSION: ${{ matrix.jekyll-version }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Run tests
      run: script/cibuild
